export const PAGES = [
  {
    id: "manage",
    landingImg: "../images/detail/desktop/image-manage-hero@2x.jpg",
    landingImgTablet: "../images/detail/tablet/image-manage-hero@2x.jpg",
    landingImgMobile: "../images/detail/mobile/image-manage-hero@2x.jpg",
    title: "Manage",
    para: "This project required me to build a fully responsive landing page to the designs provided. I used HTML5, along with CSS Grid and JavaScript for the areas that required interactivity, such as the testimonial slider.",
    tags: "Interaction Design / Front End Development",
    tech: "HTML / CSS / JS",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It’s a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I’ve learned something new with each project, helping me to improve and adapt my style.",
    previewOne: "../images/detail/desktop/image-manage-preview-1@2x.jpg",
    previewOneTablet: "../images/detail/tablet/image-manage-preview-1@2x.jpg",
    previewOneMobile: "../images/detail/mobile/image-manage-preview-1@2x.jpg",
    previewTwo: "../images/detail/desktop/image-manage-preview-2@2x.jpg",
    previewTwoTablet: "../images/detail/tablet/image-manage-preview-2@2x.jpg",
    previewTwoMobile: "../images/detail/mobile/image-manage-preview-2@2x.jpg",
    previous: "Fylo",
    next: "Bookmark",
  },
  {
    id: "bookmark",
    landingImg: "../images/detail/desktop/image-bookmark-hero@2x.jpg",
    landingImgTablet: "../images/detail/tablet/image-bookmark-hero@2x.jpg",
    landingImgMobile: "../images/detail/mobile/image-bookmark-hero@2x.jpg",
    title: "Bookmark",
    para: "This project required me to build a fully responsive landing page to the designs provided. I used HTML5, along with CSS Grid and JavaScript for the areas that required interactivity, such as the features section.",
    tags: "Interaction Design / Front End Development",
    tech: "HTML / CSS / JS",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It’s a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I’ve learned something new with each project, helping me to improve and adapt my style.",
    previewOne: "../images/detail/desktop/image-bookmark-preview-1@2x.jpg",
    previewOneTablet: "../images/detail/tablet/image-bookmark-preview-1@2x.jpg",
    previewOneMobile: "../images/detail/mobile/image-bookmark-preview-1@2x.jpg",
    previewTwo: "../images/detail/desktop/image-bookmark-preview-2@2x.jpg",
    previewTwoTablet: "../images/detail/tablet/image-bookmark-preview-2@2x.jpg",
    previewTwoMobile: "../images/detail/mobile/image-bookmark-preview-2@2x.jpg",
    previous: "Manage",
    next: "Insure",
  },
  {
    id: "insure",
    landingImg: "../images/detail/desktop/image-insure-hero@2x.jpg",
    landingImgTablet: "../images/detail/tablet/image-insure-hero@2x.jpg",
    landingImgMobile: "../images/detail/mobile/image-insure-hero@2x.jpg",
    title: "Insure",
    para: "This was a small project which mostly consisted of HTML and CSS. I built a fully-responsive landing page. The only JavaScript this project required was to enable the toggling of the mobile navigation.",
    tags: "Interaction Design / Front End Development",
    tech: "HTML / CSS / JS",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It’s a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I’ve learned something new with each project, helping me to improve and adapt my style.",
    previewOne: "../images/detail/desktop/image-insure-preview-1@2x.jpg",
    previewOneTablet: "../images/detail/tablet/image-insure-preview-1@2x.jpg",
    previewOneMobile: "../images/detail/mobile/image-insure-preview-1@2x.jpg",
    previewTwo: "../images/detail/desktop/image-insure-preview-2@2x.jpg",
    previewTwoTablet: "../images/detail/tablet/image-insure-preview-2@2x.jpg",
    previewTwoMobile: "../images/detail/mobile/image-insure-preview-2@2x.jpg",
    previous: "Bookmark",
    next: "Fylo",
  },
  {
    id: "fylo",
    landingImg: "../images/detail/desktop/image-fylo-hero@2x.jpg",
    landingImgTablet: "../images/detail/tablet/image-fylo-hero@2x.jpg",
    landingImgMobile: "../images/detail/mobile/image-fylo-hero@2x.jpg",
    title: "Fylo",
    para: "This project was built in pure HTML and CSS. I had mobile and desktop designs to work to and built it so that it was fully-responsive. I took a mobile-first approach and used modern CSS like Flexbox and Grid for layout purposes.",
    tags: "Interaction Design / Front End Development",
    tech: "HTML / CSS / JS",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It’s a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I’ve learned something new with each project, helping me to improve and adapt my style.",
    previewOne: "../images/detail/desktop/image-fylo-preview-1@2x.jpg",
    previewOneTablet: "../images/detail/tablet/image-fylo-preview-1@2x.jpg",
    previewOneMobile: "../images/detail/mobile/image-fylo-preview-1@2x.jpg",
    previewTwo: "../images/detail/desktop/image-fylo-preview-2@2x.jpg",
    previewTwoTablet: "../images/detail/tablet/image-fylo-preview-2@2x.jpg",
    previewTwoMobile: "../images/detail/mobile/image-fylo-preview-2@2x.jpg",
    previous: "Insure",
    next: "Manage",
  },
];
